### PR TITLE
hotfix: get by rating results missing typename

### PR DESCRIPTION
**Pull request by r2binx**
Closes alphahorizonio/consumat.io#147

### CODE REVIEW

**Review by JakWai01 — CHANGES_REQUESTED** [review]
Please actually query the values for rating_user, watch_status and favorite

**Comment by r2binx** [comment]
Sure, it was only meant as a quick fix though. However, then we should probably do some refactoring on that part and maybe create some kind of factory, otherwise there will be loads of duplicate code.

**Comment by r2binx** [comment]
Closes https://github.com/alphahorizonio/consumat.io/issues/147

**Review by JakWai01 — APPROVED** [review]
LGTM

**Pull request merged**
